routes/web.php
<?php


//website routes
Route::get('/', 'RideController@index');
Route::get('/register', 'StudentController@showRegisterForm')->name('user.create');
Route::post('/register', 'StudentController@store')->name('user.store');
Route::get('/show-login', 'StudentController@showLoginForm')->name('user.loginForm');
Route::get('my-booking', 'RideController@myBooking')->name('booking.me')->middleware('auth');
Route::delete('my-booking/{booking}', 'RideController@deleteMyBooking')->name('deleteMyBooking')->middleware('auth');

Route::view('/admin/login', 'admin.login');
Route::post('/admin/login', 'Admin\AdminLoginController@login')->name('admin.login.submit');
Route::post('/admin/logout', 'Admin\AdminLoginController@logout')->name('admin.logout');


Route::get('/home', function () {
    return redirect()->to('/');
});

Route::get('rides/{ride}', 'RideController@book')->name('rides.book')->middleware('auth');
Route::resource('rides', 'RideController')->only(['index']);
Auth::routes(['register' => false]);

// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth:admin']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('users', 'UsersController');
    Route::resource('buses', 'BusesController');
    Route::resource('rides', 'RidesController');
    Route::resource('bookings', 'BookingsController');
});

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth:admin']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

app/Booking.php
<?php

namespace App;

use App\Notifications\BookingStatusChangeNotification;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;
use Illuminate\Support\Facades\Notification;

class Booking extends Model
{

    public $table = 'bookings';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    const STATUS_SELECT = [
        'processing' => 'Processing',
        'confirmed'  => 'Confirmed',
        'rejected'   => 'Rejected',
    ];

    public $timestamps = false;

    protected $fillable = [
        'ride_id',
        'student_id',
        'status',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public static function booting()
    {
//        self::updated(function (Booking $booking) {
//            if ($booking->isDirty('status') && in_array($booking->status, ['confirmed', 'rejected'])) {
//                Notification::route('mail', $booking->email)->notify(new BookingStatusChangeNotification($booking->status));
//            }
//        });
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function ride()
    {
        return $this->belongsTo(Ride::class, 'ride_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'student_id');
    }
}

app/Http/Controllers/Admin/BookingsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Booking;
use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyBookingRequest;
use App\Http\Requests\StoreBookingRequest;
use App\Http\Requests\UpdateBookingRequest;
use App\Ride;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class BookingsController extends Controller
{
    public function index()
    {
        $bookings = Booking::all();
        $rides = Ride::get();
        $selectedRide = null;
        if (request()->input('ride_id')) {
            $selectedRide = optional($rides->find(request()->input('ride_id')))->route;
        }
        return view('admin.bookings.index', compact('bookings', 'rides', 'selectedRide'));
    }

    public function create()
    {
        $rides = Ride::all()->pluck('route', 'id')->prepend(trans('global.pleaseSelect'), '');
        return view('admin.bookings.create', compact('rides'));
    }

    public function store(StoreBookingRequest $request)
    {
        $booking = Booking::create($request->all());
        return redirect()->route('admin.bookings.index');
    }

    public function edit(Booking $booking)
    {
        $rides = Ride::all()->pluck('route', 'id')->prepend(trans('global.pleaseSelect'), '');
        $booking->load('ride');
        return view('admin.bookings.edit', compact('rides', 'booking'));
    }

    public function update(UpdateBookingRequest $request, Booking $booking): RedirectResponse
    {
        $booking->update($request->all());
        return redirect()->route('admin.bookings.index');
    }

    public function show(Booking $booking)
    {
        $booking->load('ride');
        return view('admin.bookings.show', compact('booking'));
    }

    public function destroy(Booking $booking)
    {
        $booking->delete();
        return back();
    }
}

resources/views/admin/bookings/create.blade.php
@extends('admin.layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.booking.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.bookings.store") }}" enctype="multipart/form-data">
            @csrf
            @include('admin.bookings.form')
        </form>
    </div>
</div>



@endsection

resources/views/admin/bookings/edit.blade.php
@extends('admin.layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.booking.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.bookings.update", [$booking->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            @include('admin.bookings.form')
        </form>
    </div>
</div>



@endsection

resources/views/admin/bookings/form.blade.php
<div class="row">
    <div class="form-group col-md-4">
        <label class="required" for="ride_id">{{ trans('cruds.booking.fields.ride') }}</label>
        <select class="form-control select2 {{ $errors->has('ride') ? 'is-invalid' : '' }}" name="ride_id" id="ride_id" required>
            @foreach($rides as $id => $ride)
{{--                <option value="{{ $id }}" {{ old('ride_id') == $id ? 'selected' : '' }}>{{ $ride }}</option>--}}
                <option value="{{ $id }}" {{ (isset($booking) && $booking->ride ? $booking->ride->id : old('ride_id')) == $id ? 'selected' : '' }}>{{ $ride }}</option>
            @endforeach
        </select>
        @if($errors->has('ride'))
            <div class="invalid-feedback">
                {{ $errors->first('ride') }}
            </div>
        @endif
    </div>
    <div class="form-group col-md-4">
        <label class="required" for="name">{{ trans('cruds.booking.fields.name') }}</label>
        <input readonly class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ isset($booking) ? optional($booking->user)->name : old('name', '') }}" required>
        @if($errors->has('name'))
            <div class="invalid-feedback">
                {{ $errors->first('name') }}
            </div>
        @endif
    </div>
    <div class="form-group col-md-4">
        <label class="required" for="email">{{ trans('cruds.booking.fields.email') }}</label>
        <input readonly class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" type="email" name="email" id="email" value="{{  isset($booking) ? optional($booking->user)->email :  old('email') }}" required>
        @if($errors->has('email'))
            <div class="invalid-feedback">
                {{ $errors->first('email') }}
            </div>
        @endif
    </div>
    <div class="form-group col-md-4">
        <label class="required" for="phone">{{ trans('cruds.booking.fields.phone') }}</label>
        <input readonly class="form-control {{ $errors->has('phone') ? 'is-invalid' : '' }}" type="text" name="phone" id="phone" value="{{ isset($booking) ? optional($booking->user)->phone :  old('phone', '') }}" required>
        @if($errors->has('phone'))
            <div class="invalid-feedback">
                {{ $errors->first('phone') }}
            </div>
        @endif
    </div>
    <div class="form-group col-md-4">
        <label class="required">{{ trans('cruds.booking.fields.status') }}</label>
        <select  class="form-control {{ $errors->has('status') ? 'is-invalid' : '' }}" name="status" id="status" required>
            <option value disabled {{ old('status', null) === null ? 'selected' : '' }}>{{ trans('global.pleaseSelect') }}</option>
            @foreach(App\Booking::STATUS_SELECT as $key => $label)
                <option value="{{ $key }}" {{ isset($booking) && old('status', $booking->status) === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
            @endforeach
        </select>
        @if($errors->has('status'))
            <div class="invalid-feedback">
                {{ $errors->first('status') }}
            </div>
        @endif
    </div>
    <div class="form-group col-md-6">
        <button class="btn btn-danger" type="submit">
            {{ trans('global.save') }}
        </button>
    </div>
</div>

resources/views/admin/bookings/index.blade.php
@extends('admin.layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        عرض قائمة الحجوزات
    </div>

    <div class="card-body">
        <div class="">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">#</th>
                        <th>{{ trans('cruds.booking.fields.ride') }}</th>
                        <th>{{ trans('cruds.booking.fields.name') }}</th>
                        <th>{{ trans('cruds.booking.fields.email') }}</th>
                        <th>العنوان</th>
                        <th>{{ trans('cruds.booking.fields.phone') }}</th>
                        <th>{{ trans('cruds.booking.fields.status') }}</th>
                        <th>العمليات</th>
                    </tr>

                </thead>
                <tbody>
                    @foreach($bookings as $key => $booking)
                        <tr data-entry-id="{{ $booking->id }}">
                            <td>{{ $booking->id }}</td>
                            <td>{{ $booking->ride->route}}</td>
                            <td>{{ optional($booking->user)->name }}</td>
                            <td>{{ optional($booking->user)->email }}</td>
                            <td>{{ optional($booking->user)->address  }}</td>
                            <td>{{ optional($booking->user)->phone  }}</td>
                            <td>{{ App\Booking::STATUS_SELECT[$booking->status] }}</td>
                            <td>
                                <a class="btn btn-xs btn-primary"
                                   href="{{ route('admin.bookings.show', $booking->id) }}">
                                    {{ trans('global.view') }}
                                </a>
                                <a class="btn btn-xs btn-info" href="{{ route('admin.bookings.edit', $booking->id) }}">
                                    {{ trans('global.edit') }}
                                </a>
                                <form action="{{ route('admin.bookings.destroy', $booking->id) }}" method="POST"
                                      onsubmit="return confirm('{{ trans('global.areYouSure') }}');"
                                      style="display: inline-block;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type="submit" class="btn btn-xs btn-danger"
                                           value="{{ trans('global.delete') }}">
                                </form>
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/admin/bookings/show.blade.php
@extends('admin.layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.booking.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.bookings.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.booking.fields.id') }}
                        </th>
                        <td>
                            {{ $booking->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.booking.fields.ride') }}
                        </th>
                        <td>
                            {{ $booking->ride->route ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.booking.fields.name') }}
                        </th>
                        <td>
                            {{ optional($booking->user)->name  }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.booking.fields.email') }}
                        </th>
                        <td>
                            {{optional($booking->user)->email  }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.booking.fields.phone') }}
                        </th>
                        <td>
                            {{ optional($booking->user)->phone  }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.booking.fields.status') }}
                        </th>
                        <td>
                            {{ App\Booking::STATUS_SELECT[$booking->status] ?? '' }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.bookings.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection