routes/web.php
<?php


//website routes
Route::get('/', 'RideController@index');
Route::get('/register', 'StudentController@showRegisterForm')->name('user.create');
Route::post('/register', 'StudentController@store')->name('user.store');
Route::get('/show-login', 'StudentController@showLoginForm')->name('user.loginForm');
Route::get('my-booking', 'RideController@myBooking')->name('booking.me')->middleware('auth');
Route::delete('my-booking/{booking}', 'RideController@deleteMyBooking')->name('deleteMyBooking')->middleware('auth');

Route::view('/admin/login', 'admin.login');
Route::post('/admin/login', 'Admin\AdminLoginController@login')->name('admin.login.submit');
Route::post('/admin/logout', 'Admin\AdminLoginController@logout')->name('admin.logout');


Route::get('/home', function () {
    return redirect()->to('/');
});

Route::get('rides/{ride}', 'RideController@book')->name('rides.book')->middleware('auth');
Route::resource('rides', 'RideController')->only(['index']);
Auth::routes(['register' => false]);

// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth:admin']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('users', 'UsersController');
    Route::resource('buses', 'BusesController');
    Route::resource('rides', 'RidesController');
    Route::resource('bookings', 'BookingsController');
});

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth:admin']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

app/Http/Controllers/Admin/BusesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Bus;
use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyBusRequest;
use App\Http\Requests\StoreBusRequest;
use App\Http\Requests\UpdateBusRequest;
use App\Traits\UploadFile;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class BusesController extends Controller
{
    use UploadFile;

    public function index()
    {
        $buses = Bus::all();
        return view('admin.buses.index', compact('buses'));
    }

    public function create()
    {
        return view('admin.buses.create');
    }

    public function store(StoreBusRequest $request)
    {
        $data = $request->all();
        $data['image'] = $this->upload($request->image);
        $bus = Bus::create($data);
        session()->flash('message', 'تم عملية الإضافة بنجــــــاح');
        return redirect()->route('admin.buses.index');
    }

    public function edit(Bus $bus)
    {
        return view('admin.buses.edit', compact('bus'));
    }

    public function update(UpdateBusRequest $request, Bus $bus)
    {
        $data = $request->all();
        if ($request->has('image')) {
            $data['image'] = $this->upload($request->image);
        }
        $bus->update($data);
        session()->flash('message', 'تم عملية التعديل بنجــــــاح');
        return redirect()->route('admin.buses.index');
    }

    public function show(Bus $bus)
    {
        return view('admin.buses.show', compact('bus'));
    }

    public function destroy(Bus $bus)
    {
        $bus->delete();
        session()->flash('message', 'تم عملية الحذف بنجــــــاح');
        return back();
    }

    public function massDestroy(MassDestroyBusRequest $request)
    {
        Bus::whereIn('id', request('ids'))->delete();
        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/buses/create.blade.php
@extends('admin.layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.bus.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.buses.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.bus.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label class="required" for="places_available">{{ trans('cruds.bus.fields.places_available') }}</label>
                <input class="form-control {{ $errors->has('places_available') ? 'is-invalid' : '' }}" type="number" name="places_available" id="places_available" value="{{ old('places_available', '') }}" step="1" required>
                @if($errors->has('places_available'))
                    <div class="invalid-feedback">
                        {{ $errors->first('places_available') }}
                    </div>
                @endif
            </div>

            <div class="form-group">
                <label class="required" for="places_available">صورة الباص</label>
                <input class="form-control {{ $errors->has('image') ? 'is-invalid' : '' }}" type="file" name="image" value="{{ old('image', '') }}" required>
                @if($errors->has('image'))
                    <div class="invalid-feedback">
                        {{ $errors->first('image') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/buses/edit.blade.php
@extends('admin.layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.bus.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.buses.update", [$bus->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.bus.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $bus->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <label class="required" for="places_available">{{ trans('cruds.bus.fields.places_available') }}</label>
                <input class="form-control {{ $errors->has('places_available') ? 'is-invalid' : '' }}" type="number" name="places_available" id="places_available" value="{{ old('places_available', $bus->places_available) }}" step="1" required>
                @if($errors->has('places_available'))
                    <div class="invalid-feedback">
                        {{ $errors->first('places_available') }}
                    </div>
                @endif
            </div>

            <div class="form-group">
                <label class="required" for="places_available">صورة الباص</label>
                <input class="form-control {{ $errors->has('image') ? 'is-invalid' : '' }}" type="file" name="image" value="{{ old('image', '') }}">
                @if($errors->has('image'))
                    <div class="invalid-feedback">
                        {{ $errors->first('image') }}
                    </div>
                @endif
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/buses/index.blade.php
@extends('admin.layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        <a class="btn btn-outline-primary" href="{{ route('admin.buses.create') }}">
            <i class="fa fa-plus"></i>
            إضافة
        </a>

        عرض قائمة الباصات
    </div>

    <div class="card-body">
        <div class="">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">#</th>
                        <th>رقم الباص</th>
                        <th>{{ trans('cruds.bus.fields.name') }}</th>
                        <th>{{ trans('cruds.bus.fields.places_available') }}</th>
                        <th>صــورة الباص</th>
                        <th>&nbsp;العمليات</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($buses as $key => $bus)
                        <tr data-entry-id="{{ $bus->id }}">
                            <td> {{$key + 1}}</td>
                            <td>{{ $bus->id ?? '' }}</td>
                            <td>{{ $bus->name ?? '' }}</td>
                            <td>{{ $bus->places_available ?? '' }}</td>
                            <td><img src="{{$bus->image_path}}" class="img-thumbnail" height="100px" width="100px"></td>
                            <td>
                                <a class="btn btn-xs btn-primary" href="{{ route('admin.buses.show', $bus->id) }}">
                                    {{ trans('global.view') }}
                                </a>
                                <a class="btn btn-xs btn-info" href="{{ route('admin.buses.edit', $bus->id) }}">
                                    {{ trans('global.edit') }}
                                </a>
                                <form action="{{ route('admin.buses.destroy', $bus->id) }}" method="POST"
                                      onsubmit="return confirm('{{ trans('global.areYouSure') }}');"
                                      style="display: inline-block;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                </form>
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/admin/buses/show.blade.php
@extends('admin.layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.bus.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.buses.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                          رقم الباص
                        </th>
                        <td>
                            {{ $bus->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.bus.fields.name') }}
                        </th>
                        <td>
                            {{ $bus->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.bus.fields.places_available') }}
                        </th>
                        <td>
                            {{ $bus->places_available }}
                        </td>
                    </tr>
                <tr>
                    <th>
                      صورة الباص
                    </th>
                    <td>
                        <img src="{{$bus->image_path}}" class="img-thumbnail" height="200px" width="200px">
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.buses.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection