routes/web.php
<?php


//website routes
Route::get('/', 'RideController@index');
Route::get('/register', 'StudentController@showRegisterForm')->name('user.create');
Route::post('/register', 'StudentController@store')->name('user.store');
Route::get('/show-login', 'StudentController@showLoginForm')->name('user.loginForm');
Route::get('my-booking', 'RideController@myBooking')->name('booking.me')->middleware('auth');
Route::delete('my-booking/{booking}', 'RideController@deleteMyBooking')->name('deleteMyBooking')->middleware('auth');

Route::view('/admin/login', 'admin.login');
Route::post('/admin/login', 'Admin\AdminLoginController@login')->name('admin.login.submit');
Route::post('/admin/logout', 'Admin\AdminLoginController@logout')->name('admin.logout');


Route::get('/home', function () {
    return redirect()->to('/');
});

Route::get('rides/{ride}', 'RideController@book')->name('rides.book')->middleware('auth');
Route::resource('rides', 'RideController')->only(['index']);
Auth::routes(['register' => false]);

// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth:admin']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('users', 'UsersController');
    Route::resource('buses', 'BusesController');
    Route::resource('rides', 'RidesController');
    Route::resource('bookings', 'BookingsController');
});

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth:admin']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

resources/views/admin/partials/menu.blade.php
<div id="sidebar" class="c-sidebar c-sidebar-fixed c-sidebar-lg-show">

    <div class="c-sidebar-brand d-md-down-none">
        <a class="c-sidebar-brand-full h4" href="#">
            احجـــزلى
        </a>
    </div>

    <ul class="c-sidebar-nav">
        <li class="c-sidebar-nav-item">
            <a href="{{ route("admin.home") }}" class="c-sidebar-nav-link">
                <i class="c-sidebar-nav-icon fas fa-fw fa-tachometer-alt">

                </i>
                {{ trans('global.dashboard') }}
            </a>
        </li>

        <li class="c-sidebar-nav-item">
            <a href="{{ route("admin.users.index") }}" class="c-sidebar-nav-link">
                <i class="c-sidebar-nav-icon fas fa-fw fa-user-alt">

                </i>
                {{ trans('cruds.userManagement.title') }}
            </a>
        </li>
        <li class="c-sidebar-nav-item">
            <a href="{{ route("admin.buses.index") }}"
               class="c-sidebar-nav-link {{ request()->is('admin/buses') || request()->is('admin/buses/*') ? 'active' : '' }}">
                <i class="fa-fw fas fa-bus c-sidebar-nav-icon">

                </i>
                {{ trans('cruds.bus.title') }}
            </a>
        </li>
        <li class="c-sidebar-nav-item">
            <a href="{{ route("admin.rides.index") }}"
               class="c-sidebar-nav-link {{ request()->is('admin/rides') || request()->is('admin/rides/*') ? 'active' : '' }}">
                <i class="fa-fw fas fa-map-marked c-sidebar-nav-icon">

                </i>
                {{ trans('cruds.ride.title') }}
            </a>
        </li>
        <li class="c-sidebar-nav-item">
            <a href="{{ route("admin.bookings.index") }}"
               class="c-sidebar-nav-link {{ request()->is('admin/bookings') || request()->is('admin/bookings/*') ? 'active' : '' }}">
                <i class="fa-fw fas fa-user c-sidebar-nav-icon">

                </i>
                {{ trans('cruds.booking.title') }}
            </a>
        </li>
        <li class="c-sidebar-nav-item">
            <a class="c-sidebar-nav-link {{ request()->is('profile/password') || request()->is('profile/password/*') ? 'active' : '' }}"
               href="{{ route('profile.password.edit') }}">
                <i class="fa-fw fas fa-key c-sidebar-nav-icon">
                </i>
                تغير كلمة المرور
            </a>
        </li>
        <li class="c-sidebar-nav-item">
            <a href="#" class="c-sidebar-nav-link"
               onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
                <i class="c-sidebar-nav-icon fas fa-fw fa-sign-out-alt">

                </i>
                {{ trans('global.logout') }}
            </a>
        </li>

        <li class="c-sidebar-nav-item">
            <a href="{{url('/')}}" class="c-sidebar-nav-link">
                <i class="c-sidebar-nav-icon fas fa-fw fa-globe"></i>
                زيارة الموقع
            </a>
        </li>
    </ul>

</div>